// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv54lbZTaNUjDQXn3Kfe4qotIKRqlOaBk',
    appId: '1:224104819950:web:3197059188b2e38b8f57ff',
    messagingSenderId: '224104819950',
    projectId: 'app-news-551a4',
    authDomain: 'app-news-551a4.firebaseapp.com',
    storageBucket: 'app-news-551a4.appspot.com',
    measurementId: 'G-H1LFX0NXDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRNHWI_d8vUDl159b_Mwa_0l94CUQXxsg',
    appId: '1:224104819950:android:41e6cf40f268367c8f57ff',
    messagingSenderId: '224104819950',
    projectId: 'app-news-551a4',
    storageBucket: 'app-news-551a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACM_ohvkm1k_JXMx3Z8ijEjpJnfYEyrUU',
    appId: '1:224104819950:ios:412a4f25a792b3db8f57ff',
    messagingSenderId: '224104819950',
    projectId: 'app-news-551a4',
    storageBucket: 'app-news-551a4.appspot.com',
    androidClientId: '224104819950-7251uj82k0s6fb7pfjj0jg6hts29alto.apps.googleusercontent.com',
    iosClientId: '224104819950-o4fhc2aq7cph9jhkf4b69vki4com5kal.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDashboardNews',
  );
}
